### PR TITLE
fix(details): manually sanitize relative svgs

### LINKED ISSUE #692: Broken images when using relative paths to SVG (compared to PNG)
*This is a joint issue for both NPM & Yarn caused by how `raw.githubusercontent.com` misidentifies certain file types.*

**TD;LR**

I created a sample package with a README and details:
  * **GitHub**: https://github.com/code-therapy/packages-with-readme-relative-images
  * **NPM**: https://www.npmjs.com/package/@code-therapy/packages-with-readme-relative-images
  * **Yarn**: https://yarnpkg.com/en/package/@code-therapy/packages-with-readme-relative-images

**Recommendations**

* Maybe GitHub can have a cross-origin policy for trusted referrers like npm & yarn.
* Maybe NPM can devise a way for packages to provide README with embedded content.
* Maybe you could use or borrow something from how rawgit handles this.

Thanks

---

NPM issue: npm/marky-markdown#420

### PR DESCRIPTION
**Pull request by Haroenv**
GitHub will return the wrong content-type and it will result in a broken image. This fix is only added in situations where String has `endsWith`, but that's okay since it's a very niche usecase

check: `@code-therapy/packages-with-readme-relative-images`

fixes #692 

cc @smotaal

### CODE REVIEW

**Comment by Haroenv** [comment]
Deploy preview ready!

Built with commit 10fb4ff5512233012f9d96f715265935ba152b95

https://deploy-preview-693--yarnpkg.netlify.com

**Comment by Haroenv** [comment]
screen shot 2017-10-29 at 07 38 18

I think the side effect when you _actually_ link raw.githubusercontent yourself is okay. Since that doesn't work on GitHub either so there should not be a reason to do it until they use the correct content type

File: js/src/lib/Details/Markdown.js [hunk 1]
```diff
@@ -26,8 +26,19 @@ const renderAndEscapeMarkdown = ({ source, githubRepo }) => {
         path,
       });
 
+    // manually ask for sanitation of svgs, otherwise it will have wrong content-type
+    const sanitize = href =>
+      `${href}${href.indexOf('//') === -1 &&
+      String.prototype.endsWith &&
+      href.endsWith('.svg')
+        ? '?sanitize=true'
+        : ''}`;
```
Comment (Daniel15) [inline js/src/lib/Details/Markdown.js]: This is very hard to read. Can you please make it a bit clearer? Also, shouldn't this only be done for relative links? Won't this current implementation add `?sanitize=true` for all SVG links, even if they're not GitHub links?

Comment (Daniel15) [inline js/src/lib/Details/Markdown.js]: This is very hard to read, since it contains a multiline template string which contains a ternary. Can you please make it a bit clearer?  For example, something like:
```
function sanitize(href) {
  if (!href.endsWith('.svg')) {
    return href;
  }
  return href + '?sanitize=true';
}
```


Also, shouldn't this only be done for relative links? Won't this current implementation add `?sanitize=true` for all SVG links, even if they're not GitHub links?

Comment (Haroenv) [reply js/src/lib/Details/Markdown.js]: it was already done only on relative links, made the conditional clearer now though
