### PR TITLE
fix(detail): make changing languages work

### LINKED ISSUE #439: Changing language while on /package/xxx links to /package/
This is because the language dropdown is rendered by Jekyll, which doesn't have knowledge about the frontend route. 

This can be fixed by doing a `.forEach` over the language dropdown (like in production.js) and replace the link by /package/xxx.

### PR DESCRIPTION
**Pull request by Haroenv**
Since the url isn't aware of which package detail we're on, we need to set the url to the correct package.

Doesn't work in `dev`, because `dev` doesn't have i18n

fixes #439 

PR deploy: https://deploy-preview-440--yarnpkg.netlify.com/zh-Hans/package/test

### CODE REVIEW

File: js/src/package.js [hunk 1]
```diff
@@ -11,7 +11,22 @@ const id = process.env.NODE_ENV == 'production'
   ? location.pathname.split('/').slice(3).join('/')
   : location.search.substring(1);
 
+if (!NodeList.prototype.forEach) {
+  NodeList.prototype.forEach = Array.prototype.forEach;
```
Comment (Daniel15) [inline js/src/package.js]: It seems unnecessary to extend the prototype... Just do a regular `for` loop instead.

Comment (Haroenv) [inline js/src/package.js]: Sure. We're extending the prototype for the same already in production.js though

Comment (Haroenv) [inline js/src/package.js]: Changed it to `for` now 😄
